//! CLI command implementations.

pub mod auth;
pub mod commit;
pub mod completions;
pub mod decide;
pub mod decide_eval;
pub mod doctor;
pub mod issue;
pub mod issue_precheck;
pub mod label;
pub mod list_args;
pub mod output;
pub mod pipeline;
pub mod pipeline_failure;
pub mod pr;
pub mod pr_precheck;
pub mod prerequisites;
pub mod query_search;
pub mod regression_semantic;
pub mod release;
pub mod review;
pub mod skills;
pub mod skills_suggest;
pub mod update;
pub mod workflow;
pub mod workflow_context;
pub mod workflow_recommend;
pub mod workflow_semantic;
