[package]
name = "release-signer"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[[bin]]
name = "release-signer"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
rand = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
