//! gitflow-cli CLI entrypoint.
//!
//! Provides a subcommand-based CLI with:
//! - TTY-aware tracing (human-readable for terminals, JSON for pipes)
//! - `NO_COLOR` / `CLICOLOR_FORCE` support
//! - SIGPIPE reset on Unix for clean pipe-exit behaviour
//! - Graceful shutdown via `tokio::signal`
//! - Top-level error display with `miette` formatting

// Tests legitimately need to unwrap fixture data and invoke sync FS helpers.
#![cfg_attr(
    test,
    allow(
        clippy::expect_used,
        clippy::unwrap_used,
        clippy::indexing_slicing,
        clippy::disallowed_methods,
        reason = "Tests legitimately need to unwrap fixture data and invoke sync FS helpers"
    )
)]

/// Build-time metadata generated by the `built` crate.
///
/// Exposes `PKG_VERSION`, `GIT_COMMIT_HASH`, `TARGET`, and similar
/// constants. Unused fields are expected because the `built` crate
/// generates a fixed set of metadata regardless of what the binary
/// actually reads.
///
/// The lint suppressions are required because the `built` crate's
/// generated source uses unhashed raw string literals, reason-less
/// `#[allow(dead_code)]` attributes, and identifier-like tokens in
/// doc comments that would otherwise fail under the workspace's
/// pedantic lint configuration.
#[allow(
    dead_code,
    reason = "Generated by `built` crate; fields referenced via built_info::"
)]
#[allow(clippy::needless_raw_string_hashes)]
#[allow(clippy::allow_attributes_without_reason)]
#[allow(clippy::doc_markdown)]
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

mod commands;
mod error_reporter;

use clap::{CommandFactory, FromArgMatches, Parser, Subcommand};
use commands::{
    auth::AuthCommand,
    commit::CommitCommand,
    completions::CompletionsArgs,
    issue::IssueCommand,
    label::{LabelCommand, MilestoneCommand},
    pr::PrCommand,
    release::ReleaseCommand,
    review::ReviewCommand,
};
use is_terminal::IsTerminal;

fn main() -> std::process::ExitCode {
    // Reset SIGPIPE on Unix so broken pipes exit cleanly
    #[cfg(unix)]
    reset_sigpipe();

    // Initialize tracing subscriber (TTY-aware, respects NO_COLOR)
    init_tracing();

    // Build version string: pkg version
    let matches = match Cli::command()
        .version(built_info::PKG_VERSION)
        .try_get_matches()
    {
        Ok(m) => m,
        Err(e) => e.exit(),
    };

    let cli = match Cli::from_arg_matches(&matches) {
        Ok(c) => c,
        Err(e) => e.exit(),
    };

    // Capture the command name before `cli` is consumed by `async_main`.
    let command_name = cli.command_name();

    // Completions are purely synchronous -- generate and exit
    if let Commands::Completions(ref args) = cli.command {
        return commands::completions::generate::<Cli>(args);
    }

    // Build the async runtime
    let rt = match tokio::runtime::Runtime::new() {
        Ok(rt) => rt,
        Err(e) => {
            let report = miette::miette!("Failed to create async runtime: {e}");
            report_error_noninteractive(
                &command_name,
                "unknown",
                &report.to_string(),
                "RUNTIME_ERROR",
            );
            eprintln!("{report:?}");
            return std::process::ExitCode::from(1);
        }
    };

    // Resolve platform and repository early so they are available in the
    // error handler below. `cli.platform` is cloned because `cli` itself
    // is moved into `async_main`.
    let (platform, repo) = match resolve_platform(cli.platform.clone()) {
        Ok(pr) => pr,
        Err(e) => {
            report_error_noninteractive(&command_name, "unknown", &e.to_string(), "PLATFORM_ERROR");
            eprintln!("{e:?}");
            return std::process::ExitCode::from(1);
        }
    };

    // Block on the async main, handling graceful shutdown signals
    match rt.block_on(async_main(cli, &platform, &repo)) {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(e) => {
            report_error_noninteractive(&command_name, &platform, &e.to_string(), "CLI_ERROR");
            eprintln!("{e:?}");
            std::process::ExitCode::from(1)
        }
    }
}

/// Best-effort error reporting for non-interactive mode.
///
/// Delegates to [`error_reporter::maybe_report_error`], silently
/// discarding any I/O errors. The error report is a diagnostic aid;
/// a failure to write it must never block or alter the exit code.
fn report_error_noninteractive(
    command: &str,
    platform: &str,
    error_message: &str,
    error_code: &str,
) {
    let _ = error_reporter::maybe_report_error(command, platform, error_message, error_code);
}

/// Async entry point that wires graceful shutdown into the main flow.
///
/// Flow: check prerequisites → dispatch command.
///
/// The `platform` and `repo` are resolved in `main()` before this
/// function is called so they remain available in the error handler.
async fn async_main(cli: Cli, platform: &str, repo: &str) -> miette::Result<()> {
    // Run native CLI prerequisite check before dispatching
    commands::prerequisites::check(platform).map_err(|e| miette::miette!("{e}"))?;

    tokio::select! {
        result = router(cli.command, platform, repo, cli.output) => result,
        () = async {
            match tokio::signal::ctrl_c().await {
                Ok(()) => tracing::info!("Received shutdown signal, exiting gracefully"),
                Err(e) => tracing::warn!("Failed to install Ctrl+C handler: {e}"),
            }
        } => {
            Ok(())
        }
    }
}

/// Dispatch a subcommand to the appropriate handler.
async fn router(
    command: Commands,
    platform: &str,
    repo: &str,
    output: OutputFormat,
) -> miette::Result<()> {
    match command {
        Commands::Issue(cmd) => commands::issue::handle(cmd, platform, repo, output).await,
        Commands::Pr(cmd) => commands::pr::handle(cmd, platform, repo, output).await,
        Commands::Release(cmd) => commands::release::handle(cmd, platform, repo, output).await,
        Commands::Review(cmd) => commands::review::handle(cmd, platform, repo, output).await,
        Commands::Auth(cmd) => commands::auth::handle(cmd, platform, repo, output).await,
        Commands::Label(cmd) => commands::label::handle_label(cmd, platform, repo, output).await,
        Commands::Milestone(cmd) => {
            commands::label::handle_milestone(cmd, platform, repo, output).await
        }
        Commands::Commit(cmd) => commands::commit::handle(cmd, platform, repo, output).await,
        Commands::SkillsInstall => Err(miette::miette!("skills install not yet implemented")),
        Commands::Run(_args) => Err(miette::miette!(
            "run command is deprecated; use specific subcommands"
        )),
        Commands::Completions(_) => Ok(()),
    }
}

/// Resolve the target platform and repository from CLI args and git remote.
///
/// Priority:
/// 1. `--platform` flag (explicit override)
/// 2. `git remote get-url origin` auto-detection
/// 3. Both fail → error with hint to use `--platform`
///
/// # Errors
///
/// - Git remote URL cannot be obtained → hint to run inside a git repo
/// - Platform cannot be detected → hint to use `--platform`
/// - `owner/repo` cannot be parsed from remote URL → parse error
#[allow(
    clippy::disallowed_types,
    reason = "Invoked before the tokio runtime is constructed"
)]
fn resolve_platform(cli_platform: Option<PlatformArg>) -> miette::Result<(String, String)> {
    // Get git remote URL
    let output = std::process::Command::new("git")
        .args(["remote", "get-url", "origin"])
        .output()
        .map_err(|e| {
            miette::miette!("Failed to get git remote URL: {e}\nAre you in a git repository?")
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(miette::miette!(
            "git remote get-url origin failed: {}\nAre you in a git repository?",
            stderr.trim()
        ));
    }

    let remote_url = String::from_utf8_lossy(&output.stdout).trim().to_string();

    // Determine platform
    let platform = if let Some(p) = cli_platform {
        match p {
            PlatformArg::Github => "github",
            PlatformArg::Gitlab => "gitlab",
            PlatformArg::Gitcode => "gitcode",
        }
        .to_string()
    } else {
        let detected = gitflow_cli_core::platform::Platform::detect_from_remote_url(&remote_url)
            .ok_or_else(|| {
                miette::miette!(
                    "Unable to detect platform from remote URL: {remote_url}\nUse --platform to \
                     specify explicitly."
                )
            })?;
        format!("{detected:?}").to_lowercase()
    };

    // Extract owner/repo
    let repo = extract_repo_from_url(&remote_url)
        .ok_or_else(|| miette::miette!("Unable to parse owner/repo from URL: {remote_url}"))?;

    Ok((platform, repo))
}

/// Extract `owner/repo` from a git remote URL.
///
/// Supports both HTTPS and SSH remote formats:
/// - `https://github.com/owner/repo.git` → `owner/repo`
/// - `git@github.com:owner/repo.git` → `owner/repo`
/// - `https://gitlab.example.com/group/project` → `group/project`
///
/// Returns `None` if the URL cannot be parsed into at least two path
/// segments after stripping the scheme and host.
#[must_use]
fn extract_repo_from_url(url: &str) -> Option<String> {
    let without_prefix = url
        .trim_start_matches("https://")
        .trim_start_matches("http://")
        .trim_start_matches("git@");

    // For SSH URLs like `host:owner/repo`, take the part after `:`.
    // For HTTPS URLs like `host/owner/repo`, there's no `:` so keep the whole path.
    let path = without_prefix
        .split_once(':')
        .map_or(without_prefix, |(_before, after)| after);

    let no_suffix = path.trim_end_matches(".git");
    let segments: Vec<&str> = no_suffix.split('/').filter(|s| !s.is_empty()).collect();

    if segments.len() >= 2 {
        let owner = segments
            .get(segments.len() - 2)
            .copied()
            .unwrap_or_default();
        let repo = segments.last().copied().unwrap_or_default();
        Some(format!("{owner}/{repo}"))
    } else {
        None
    }
}

/// Initialize the `tracing-subscriber` with TTY-aware output.
///
/// - **TTY (terminal)**: human-readable output. ANSI colours are enabled unless `NO_COLOR` is set.
/// - **Pipe / redirect**: JSON-formatted output for machine consumption, unless `CLICOLOR_FORCE` is
///   set (non-zero), which forces human-readable output with colour.
/// - `NO_COLOR` always disables ANSI escape sequences regardless of output target or
///   `CLICOLOR_FORCE`.
fn init_tracing() {
    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info"));

    let is_tty = std::io::stderr().is_terminal();
    let no_color = std::env::var("NO_COLOR").is_ok();
    let force_color = std::env::var("CLICOLOR_FORCE").is_ok_and(|v| v != "0");

    let use_json = !is_tty && !force_color;
    let use_ansi = !no_color && (is_tty || force_color);

    if use_json {
        tracing_subscriber::fmt()
            .with_env_filter(env_filter)
            .json()
            .init();
    } else {
        tracing_subscriber::fmt()
            .with_env_filter(env_filter)
            .with_ansi(use_ansi)
            .with_target(false)
            .init();
    }
}

/// Reset `SIGPIPE` to the default handler so the process exits
/// cleanly when the output pipe is broken, instead of panicking
/// with an `EPIPE` error.
///
/// This is a well-established pattern for CLI tools (used by
/// ripgrep, fd, bat, and others).
///
/// NOTE: Disabled due to `#![forbid(unsafe_code)]` policy.
/// SIGPIPE handling would require a separate crate or allow-listing unsafe code.
#[cfg(unix)]
fn reset_sigpipe() {
    // Intentionally empty - unsafe SIGPIPE reset disabled to comply with forbid(unsafe_code)
}

/// Platform argument for the `--platform` CLI flag.
///
/// Maps to the three supported hosting platforms. Used as a
/// `clap::ValueEnum` so clap generates value completions and
/// validation automatically.
#[derive(Debug, Clone, clap::ValueEnum)]
enum PlatformArg {
    /// GitHub (github.com or Enterprise).
    #[value(name = "github")]
    Github,
    /// GitLab (gitlab.com or self-hosted).
    #[value(name = "gitlab")]
    Gitlab,
    /// `GitCode` (gitcode.com or self-hosted).
    #[value(name = "gitcode")]
    Gitcode,
}

/// Output format for CLI command results.
///
/// Controls how command output is rendered to the terminal.
#[derive(Debug, Default, Clone, clap::ValueEnum)]
pub enum OutputFormat {
    /// Structured JSON output (default; for machine consumption by skills).
    #[default]
    Json,
    /// Human-readable plain text output.
    Text,
}

/// gitflow-cli command-line interface.
#[derive(Debug, Parser)]
#[command(name = "gitflow-cli", about = "gitflow-cli CLI tool", author)]
struct Cli {
    /// Override platform auto-detection.
    #[arg(long, global = true)]
    platform: Option<PlatformArg>,

    /// Output format (json or text).
    #[arg(long, global = true, default_value = "json")]
    output: OutputFormat,

    /// Enable verbose output.
    #[arg(short, long, global = true)]
    verbose: bool,

    #[command(subcommand)]
    command: Commands,
}

impl Cli {
    /// Return the top-level subcommand name for error reporting.
    fn command_name(&self) -> String {
        match self.command {
            Commands::Issue(_) => "issue",
            Commands::Pr(_) => "pr",
            Commands::Release(_) => "release",
            Commands::Review(_) => "review",
            Commands::Auth(_) => "auth",
            Commands::SkillsInstall => "skills",
            Commands::Run(_) => "run",
            Commands::Completions(_) => "completions",
            Commands::Label(_) => "label",
            Commands::Milestone(_) => "milestone",
            Commands::Commit(_) => "commit",
        }
        .into()
    }
}

/// Available subcommands.
#[derive(Debug, Subcommand)]
enum Commands {
    /// Issue operations (create, list, view).
    #[command(subcommand)]
    Issue(IssueCommand),

    /// Pull request operations (create, list, view).
    #[command(subcommand)]
    Pr(PrCommand),

    /// Release operations (create, list, view, edit, upload, download, delete).
    #[command(subcommand)]
    Release(ReleaseCommand),

    /// Code review operations (comment, approve, request-changes, submit).
    #[command(subcommand)]
    Review(ReviewCommand),

    /// Authentication operations (login, logout, status, token).
    #[command(subcommand)]
    Auth(AuthCommand),

    /// Label operations (create, list, edit, delete).
    #[command(subcommand)]
    Label(LabelCommand),

    /// Milestone operations (create, list, edit, close, reopen).
    #[command(subcommand)]
    Milestone(MilestoneCommand),

    /// Commit operations (view, diff, patch, comment).
    #[command(subcommand)]
    Commit(CommitCommand),

    /// Install gitflow skills to `~/.claude/skills/`.
    #[command(name = "skills")]
    SkillsInstall,

    /// Run the main application workflow (deprecated).
    Run(commands::run::RunArgs),

    /// Generate shell completion scripts.
    #[command(hide = true)]
    Completions(CompletionsArgs),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_should_extract_repo_from_https_url() {
        let url = "https://github.com/owner/repo.git";
        assert_eq!(extract_repo_from_url(url), Some("owner/repo".to_string()));
    }

    #[test]
    fn test_should_extract_repo_from_ssh_url() {
        let url = "git@github.com:owner/repo.git";
        assert_eq!(extract_repo_from_url(url), Some("owner/repo".to_string()));
    }

    #[test]
    fn test_should_extract_repo_without_dot_git_suffix() {
        let url = "https://github.com/owner/repo";
        assert_eq!(extract_repo_from_url(url), Some("owner/repo".to_string()));
    }

    #[test]
    fn test_should_return_none_for_invalid_url() {
        assert_eq!(extract_repo_from_url("just-a-string"), None);
        assert_eq!(extract_repo_from_url(""), None);
        assert_eq!(extract_repo_from_url("https://github.com"), None);
    }
}
