//! gitflow-cli CLI entrypoint.
//!
//! Provides a subcommand-based CLI with:
//! - TTY-aware tracing (human-readable for terminals, JSON for pipes)
//! - `NO_COLOR` / `CLICOLOR_FORCE` support
//! - SIGPIPE reset on Unix for clean pipe-exit behaviour
//! - Graceful shutdown via `tokio::signal`
//! - Top-level error display with `miette` formatting

pub mod built_info {
    #![allow(dead_code, reason = "Generated by `built` crate; fields referenced via built_info::")]
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

mod commands;
mod config;

use clap::{CommandFactory, FromArgMatches, Parser, Subcommand};
use is_terminal::IsTerminal;

use commands::completions::CompletionsArgs;
use commands::issue::IssueCommand;
use commands::pr::PrCommand;

fn main() -> std::process::ExitCode {
    // Reset SIGPIPE on Unix so broken pipes exit cleanly
    #[cfg(unix)]
    reset_sigpipe();

    // Initialize tracing subscriber (TTY-aware, respects NO_COLOR)
    init_tracing();

    // Build version string: pkg version
    let matches = match Cli::command().version(built_info::PKG_VERSION).try_get_matches() {
        Ok(m) => m,
        Err(e) => e.exit(),
    };

    let cli = match Cli::from_arg_matches(&matches) {
        Ok(c) => c,
        Err(e) => e.exit(),
    };

    // Completions are purely synchronous -- generate and exit
    if let Commands::Completions(ref args) = cli.command {
        return commands::completions::generate::<Cli>(args);
    }

    // Build the async runtime
    let rt = match tokio::runtime::Runtime::new() {
        Ok(rt) => rt,
        Err(e) => {
            let report = miette::miette!("Failed to create async runtime: {e}");
            eprintln!("{report:?}");
            return std::process::ExitCode::from(1);
        }
    };

    // Block on the async main, handling graceful shutdown signals
    match rt.block_on(async_main(cli)) {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("{e:?}");
            std::process::ExitCode::from(1)
        }
    }
}

/// Async entry point that wires graceful shutdown into the main flow.
///
/// Flow: resolve platform → check prerequisites → dispatch command.
async fn async_main(cli: Cli) -> miette::Result<()> {
    // Resolve target platform and repository from git remote
    let (platform, repo) = resolve_platform(cli.platform)?;

    // Run native CLI prerequisite check before dispatching
    commands::prerequisites::check(&platform)
        .map_err(|e| miette::miette!("{e}"))?;

    tokio::select! {
        result = router(cli.command, &platform, &repo, cli.output) => result,
        () = async {
            match tokio::signal::ctrl_c().await {
                Ok(()) => tracing::info!("Received shutdown signal, exiting gracefully"),
                Err(e) => tracing::warn!("Failed to install Ctrl+C handler: {e}"),
            }
        } => {
            Ok(())
        }
    }
}

/// Dispatch a subcommand to the appropriate handler.
async fn router(
    command: Commands,
    _platform: &str,
    _repo: &str,
    _output: OutputFormat,
) -> miette::Result<()> {
    match command {
        Commands::Issue(_cmd) => Err(miette::miette!("issue command not yet implemented (Task 10)")),
        Commands::Pr(_cmd) => Err(miette::miette!("pr command not yet implemented (Task 11)")),
        Commands::SkillsInstall => Err(miette::miette!("skills install not yet implemented")),
        Commands::Run(_args) => Err(miette::miette!("run command is deprecated; use specific subcommands")),
        Commands::Completions(_) => Ok(()),
    }
}

/// Resolve the target platform and repository from CLI args and git remote.
///
/// Priority:
/// 1. `--platform` flag (explicit override)
/// 2. `git remote get-url origin` auto-detection
/// 3. Both fail → error with hint to use `--platform`
///
/// # Errors
///
/// - Git remote URL cannot be obtained → hint to run inside a git repo
/// - Platform cannot be detected → hint to use `--platform`
/// - `owner/repo` cannot be parsed from remote URL → parse error
fn resolve_platform(cli_platform: Option<PlatformArg>) -> miette::Result<(String, String)> {
    // Get git remote URL
    let output = std::process::Command::new("git")
        .args(["remote", "get-url", "origin"])
        .output()
        .map_err(|e| miette::miette!("Failed to get git remote URL: {e}\nAre you in a git repository?"))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(miette::miette!(
            "git remote get-url origin failed: {}\nAre you in a git repository?",
            stderr.trim()
        ));
    }

    let remote_url = String::from_utf8_lossy(&output.stdout).trim().to_string();

    // Determine platform
    let platform = match cli_platform {
        Some(p) => match p {
            PlatformArg::Github => "github",
            PlatformArg::Gitlab => "gitlab",
            PlatformArg::Gitcode => "gitcode",
        }
        .to_string(),
        None => {
            let detected =
                gitflow_cli_core::platform::Platform::detect_from_remote_url(&remote_url)
                    .ok_or_else(|| {
                        miette::miette!(
                            "Unable to detect platform from remote URL: {remote_url}\nUse --platform to specify explicitly."
                        )
                    })?;
            format!("{detected:?}").to_lowercase()
        }
    };

    // Extract owner/repo
    let repo = extract_repo_from_url(&remote_url)
        .ok_or_else(|| miette::miette!("Unable to parse owner/repo from URL: {remote_url}"))?;

    Ok((platform, repo))
}

/// Extract `owner/repo` from a git remote URL.
///
/// Supports both HTTPS and SSH remote formats:
/// - `https://github.com/owner/repo.git` → `owner/repo`
/// - `git@github.com:owner/repo.git` → `owner/repo`
/// - `https://gitlab.example.com/group/project` → `group/project`
///
/// Returns `None` if the URL cannot be parsed into at least two path
/// segments after stripping the scheme and host.
#[must_use]
fn extract_repo_from_url(url: &str) -> Option<String> {
    let without_prefix = url
        .trim_start_matches("https://")
        .trim_start_matches("http://")
        .trim_start_matches("git@");

    // For SSH URLs like `host:owner/repo`, take the part after `:`.
    // For HTTPS URLs like `host/owner/repo`, there's no `:` so keep the whole path.
    let path = without_prefix.splitn(2, ':').nth(1).unwrap_or(without_prefix);

    let no_suffix = path.trim_end_matches(".git");
    let segments: Vec<&str> = no_suffix.split('/').filter(|s| !s.is_empty()).collect();

    if segments.len() >= 2 {
        let owner = segments[segments.len() - 2];
        let repo = segments[segments.len() - 1];
        Some(format!("{owner}/{repo}"))
    } else {
        None
    }
}

/// Initialize the `tracing-subscriber` with TTY-aware output.
///
/// - **TTY (terminal)**: human-readable output. ANSI colours are
///   enabled unless `NO_COLOR` is set.
/// - **Pipe / redirect**: JSON-formatted output for machine
///   consumption, unless `CLICOLOR_FORCE` is set (non-zero),
///   which forces human-readable output with colour.
/// - `NO_COLOR` always disables ANSI escape sequences regardless
///   of output target or `CLICOLOR_FORCE`.
fn init_tracing() {
    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info"));

    let is_tty = std::io::stderr().is_terminal();
    let no_color = std::env::var("NO_COLOR").is_ok();
    let force_color = std::env::var("CLICOLOR_FORCE")
        .map(|v| v != "0")
        .unwrap_or(false);

    let use_json = !is_tty && !force_color;
    let use_ansi = !no_color && (is_tty || force_color);

    if use_json {
        tracing_subscriber::fmt()
            .with_env_filter(env_filter)
            .json()
            .init();
    } else {
        tracing_subscriber::fmt()
            .with_env_filter(env_filter)
            .with_ansi(use_ansi)
            .with_target(false)
            .init();
    }
}

/// Reset `SIGPIPE` to the default handler so the process exits
/// cleanly when the output pipe is broken, instead of panicking
/// with an `EPIPE` error.
///
/// This is a well-established pattern for CLI tools (used by
/// ripgrep, fd, bat, and others).
///
/// NOTE: Disabled due to `#![forbid(unsafe_code)]` policy.
/// SIGPIPE handling would require a separate crate or allow-listing unsafe code.
#[cfg(unix)]
fn reset_sigpipe() {
    // Intentionally empty - unsafe SIGPIPE reset disabled to comply with forbid(unsafe_code)
}

/// Platform argument for the `--platform` CLI flag.
///
/// Maps to the three supported hosting platforms. Used as a
/// `clap::ValueEnum` so clap generates value completions and
/// validation automatically.
#[derive(Debug, Clone, clap::ValueEnum)]
enum PlatformArg {
    /// GitHub (github.com or Enterprise).
    #[value(name = "github")]
    Github,
    /// GitLab (gitlab.com or self-hosted).
    #[value(name = "gitlab")]
    Gitlab,
    /// GitCode (gitcode.com or self-hosted).
    #[value(name = "gitcode")]
    Gitcode,
}

/// Output format for CLI command results.
///
/// Controls how command output is rendered to the terminal.
#[derive(Debug, Clone, clap::ValueEnum)]
enum OutputFormat {
    /// Structured JSON output (default; for machine consumption by skills).
    Json,
    /// Human-readable plain text output.
    Text,
}

impl Default for OutputFormat {
    fn default() -> Self {
        Self::Json
    }
}

/// gitflow-cli command-line interface.
#[derive(Debug, Parser)]
#[command(
    name = "gitflow-cli",
    about = "gitflow-cli CLI tool",
    author
)]
struct Cli {
    /// Override platform auto-detection.
    #[arg(long, global = true)]
    platform: Option<PlatformArg>,

    /// Output format (json or text).
    #[arg(long, global = true, default_value = "json")]
    output: OutputFormat,

    /// Enable verbose output.
    #[arg(short, long, global = true)]
    verbose: bool,

    #[command(subcommand)]
    command: Commands,
}

/// Available subcommands.
#[derive(Debug, Subcommand)]
enum Commands {
    /// Issue operations (create, list, view).
    #[command(subcommand)]
    Issue(IssueCommand),

    /// Pull request operations (create, list, view).
    #[command(subcommand)]
    Pr(PrCommand),

    /// Install gitflow skills to `~/.claude/skills/`.
    #[command(name = "skills")]
    SkillsInstall,

    /// Run the main application workflow (deprecated).
    Run(commands::run::RunArgs),

    /// Generate shell completion scripts.
    #[command(hide = true)]
    Completions(CompletionsArgs),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_should_extract_repo_from_https_url() {
        let url = "https://github.com/owner/repo.git";
        assert_eq!(extract_repo_from_url(url), Some("owner/repo".to_string()));
    }

    #[test]
    fn test_should_extract_repo_from_ssh_url() {
        let url = "git@github.com:owner/repo.git";
        assert_eq!(extract_repo_from_url(url), Some("owner/repo".to_string()));
    }

    #[test]
    fn test_should_extract_repo_without_dot_git_suffix() {
        let url = "https://github.com/owner/repo";
        assert_eq!(extract_repo_from_url(url), Some("owner/repo".to_string()));
    }

    #[test]
    fn test_should_return_none_for_invalid_url() {
        assert_eq!(extract_repo_from_url("just-a-string"), None);
        assert_eq!(extract_repo_from_url(""), None);
        assert_eq!(extract_repo_from_url("https://github.com"), None);
    }
}
